### ISSUE TITLE
The eval script fails at empty input

### ISSUE THREAD

**Issue by yanwang10** [harperco/MeasEval#2]
Hi,

Thanks for the script to evaluate the results locally. I didn't have the luck to run it successfully against my model outputs, with key errors here and there. More specifically, when running against an **empty** input (e.g. all DOC_ID.tsv files exist but with only headers without any content rows), the script fails with the following error:

```
Submission directory contains: 65
Gold directory contains: 65
Gold count of Quantity: 281
Gold count of MeasuredProperty: 179
Gold count of MeasuredEntity: 273
Gold count of Qualifier: 99

Submission count of Quantity: 0
Submission count of MeasuredProperty: 0
Submission count of MeasuredEntity: 0
Submission count of Qualifier: 0

Traceback (most recent call last):
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'gAnnotSet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/generic.py", line 3576, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'gAnnotSet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "measeval-eval.py", line 367, in <module>
    sub["gAnnotSet"] = sub.apply(lambda x: annotSetAlignmentsDict[x.docId][x.annotSet] if x.annotSet in annotSetAlignmentsDict[x.docId] else None , axis = 1)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/frame.py", line 3121, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/generic.py", line 3579, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1198, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2744, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2400, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/home/wy/anaconda3/envs/eval/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 11, placement implies 1
```

I'm not sure whether this is related to the local env. Could you share the specs of the env? The error logs above were generated with Python 3.6.12 (Anaconda) and `pip freeze` gives the following results:

```
certifi==2020.12.5
numpy==1.19.4
pandas==1.1.5
pandasql==0.7.3
python-dateutil==2.8.1
pytz==2020.5
six==1.15.0
SQLAlchemy==1.3.22
vladiate==0.0.23
```

Thanks and happy new year,
Yan

**Comment by harperco** [comment]
Hi Yan,

This should now be fixed. The evaluation was not set up to allow for empty submissions like you provided. It also could not handle submissions that lacked either units or modifiers. The latest commit accounts for these cases.

Your environment looks good to me, so if you pull the latest commit, everything should work as expected. Let me know if you encounter any further issues.

Best regards,
-Corey

**Comment by yanwang10** [comment]
Thank you Corey for the fix! The latest script runs successfully now against my model output.
